name: Send Weather Email

on:
  schedule:
    - cron: '0 7 * * *' # Setiap hari pukul 07:00 WIB

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install requests python-dateutil

      - name: Set environment variables
        run: |
          echo "ACCUWEATHER_API_KEY=${{ secrets.ACCUWEATHER_API_KEY }}" >> $GITHUB_ENV  
          echo "EMAIL_TO=${{ secrets.EMAIL_TO }}" >> $GITHUB_ENV  
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> $GITHUB_ENV  
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Fetch weather data
        run: python fetch_weather.py
        id: fetch_weather

      - name: Send email
        run: |
          echo "Subject: Ramalan Cuaca Hari Ini" > email.txt  
          echo "Berikut adalah ramalan cuaca hari ini:" >> email.txt  
          python fetch_weather.py >> email.txt  
          python send_email.py
